# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/TekWizely/pre-commit-golang
    rev: v0.8.3 # update to v1 after release from beta
    hooks:
    -   id: golangci-lint-mod
    -   id: go-sec-mod
    -   id: go-test-mod

